### ISSUE TITLE
Error at the end of flush

### ISSUE THREAD

**Issue by howardyoo** [vmware/vrops-export#22]
```
May 13, 2020 9:53:26 AM com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient internalFlush
WARNING: Error reporting points, respStatus=406
May 13, 2020 9:56:25 AM com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient close
WARNING: error flushing buffer
java.io.IOException: attempt to flush closed sender
	at com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient.flush(WavefrontDirectIngestionClient.java:357)
	at com.wavefront.sdk.direct.ingestion.WavefrontDirectIngestionClient.close(WavefrontDirectIngestionClient.java:424)
	at com.vmware.vropsexport.processors.WavefrontPusher.close(WavefrontPusher.java:96)
	at com.vmware.vropsexport.Exporter.exportTo(Exporter.java:217)
	at com.vmware.vropsexport.Main.main(Main.java:184)
```

I'm not sure why this is happening, but this happens everytime I try to run the exporter, in direct ingestion mode. Also, I randomly see 406 errors (which may not be related to the exporter itself), but want to know why that's happening in more details.

**Comment by howardyoo** [comment]
Maybe it's okay, since the message is WARNING..?
